import { addCase, getState, type CaseStatus } from "@/lib/store";
import type { DatasetSchema, FieldDef } from "./types";

// Priority mirrors delivery Priority type but decoupled here to keep the
// framework independent of consumer types.
const PRIORITY_VALUES = ["Normal", "VIP"] as const;
const DELIVERY_METHOD_VALUES = ["Home Delivery", "Airport Pickup"] as const;
const CASE_STATUS_VALUES: CaseStatus[] = [
  "Missing",
  "Located",
  "Stored",
  "Ready For Delivery",
  "Out For Delivery",
  "Delivered",
];

// ---------------- Lost & Found ----------------
// Bulk case creation template — mirrors the current PIR wizard data model.
// Mandatory fields are the minimum needed to open a case; the rest can be
// completed later. PIR Number and Bag Tag are unique — duplicates against
// existing records or within the file are rejected during validation.
const lostFoundFields: FieldDef[] = [
  // PIR Number is optional — a sequential Case ID (BAG-0000xx) is always
  // generated by the Workflow Engine. When supplied it must stay unique.
  { key: "pirNumber", label: "PIR Number", type: "string", unique: true, example: "CAIMS12045" },
  { key: "passengerName", label: "Passenger Name", type: "string", required: true, example: "Mariam Hossam" },
  { key: "mobile1", label: "Mobile 1", type: "phone", required: true, example: "+20 100 234 5512" },
  { key: "mobile2", label: "Mobile 2", type: "phone", example: "+20 101 998 2210" },
  { key: "email", label: "Email", type: "email", example: "passenger@example.com" },
  { key: "pnr", label: "PNR", type: "string", example: "X7K2QA" },
  { key: "airline", label: "Airline", type: "airlineCode", required: true, example: "MS" },
  { key: "flightNumber", label: "Flight Number", type: "string", required: true, example: "MS985" },
  { key: "flightDate", label: "Flight Date", type: "date", required: true, example: "2026-06-18" },
  { key: "origin", label: "Origin", type: "airportCode", required: true, example: "JFK" },
  { key: "destination", label: "Destination", type: "airportCode", required: true, example: "CAI" },
  { key: "bagTag", label: "Bag Tag", type: "string", required: true, unique: true, example: "MS548921" },
  { key: "numberOfBags", label: "Number of Bags", type: "integer", example: "1" },
  { key: "bagColor", label: "Color", type: "string", example: "Black" },
  { key: "weightKg", label: "Weight (kg)", type: "number", example: "18.5" },
  { key: "bagType", label: "Bag Type", type: "string", example: "Hardshell" },
  { key: "deliveryMethod", label: "Delivery Method", type: "enum", enumValues: DELIVERY_METHOD_VALUES, example: "Home Delivery" },
  { key: "deliveryAddress", label: "Delivery Address", type: "string", example: "14 Road 9, Maadi, Cairo" },
  { key: "priority", label: "Priority", type: "enum", enumValues: PRIORITY_VALUES, example: "Normal" },
  { key: "notes", label: "Notes", type: "string", example: "Silver Delsey cabin trolley" },
];

// Reserved for future read-only exports referencing legacy case status.
void CASE_STATUS_VALUES;

function isBlank(v: unknown) {
  return v === undefined || v === null || String(v).trim() === "";
}

export const lostFoundSchema: DatasetSchema = {
  id: "lost-found",
  label: "Lost & Found",
  description: "Bulk PIR case creation — passenger, flight, baggage, and delivery.",
  templateVersion: "2.0",
  fields: lostFoundFields,
  read: () => getState().cases as unknown as Record<string, unknown>[],
  apply: async (rows: Record<string, unknown>[], ctx) => {
    const ids: string[] = [];
    let created = 0;
    let warnings = 0;
    let rejected = 0;
    const optional: { key: string; label: string }[] = [
      { key: "mobile2", label: "Mobile 2" },
      { key: "email", label: "Email" },
      { key: "pnr", label: "PNR" },
      { key: "numberOfBags", label: "Number of Bags" },
      { key: "bagColor", label: "Color" },
      { key: "weightKg", label: "Weight" },
      { key: "bagType", label: "Bag Type" },
      { key: "deliveryMethod", label: "Delivery Method" },
      { key: "deliveryAddress", label: "Delivery Address" },
      { key: "priority", label: "Priority" },
      { key: "notes", label: "Notes" },
    ];
    for (const raw of rows) {
      const missingFields = optional.filter((f) => isBlank(raw[f.key])).map((f) => f.label);
      const incomplete = missingFields.length > 0;
      if (incomplete) warnings++;

      const bagTag = String(raw.bagTag ?? "").trim();
      const numBags = Number(raw.numberOfBags) > 0 ? Number(raw.numberOfBags) : 1;
      const rawPriority = raw.priority ? String(raw.priority) : "Normal";
      const priority: "Normal" | "VIP" = rawPriority === "VIP" ? "VIP" : "Normal";
      const method = raw.deliveryMethod as "Home Delivery" | "Airport Pickup" | undefined;
      const description = [raw.bagColor, raw.bagType, raw.notes]
        .filter((v) => v !== undefined && v !== null && String(v).trim() !== "")
        .join(" — ");

      let c: Awaited<ReturnType<typeof addCase>> = null;
      try {
        c = await addCase({
        passengerName: String(raw.passengerName ?? "").trim(),
        flightNumber: String(raw.flightNumber ?? ""),
        pirNumber: String(raw.pirNumber ?? "").trim(),
        bagTagNumber: bagTag,
        arrivalDate: String(raw.flightDate ?? new Date().toISOString().slice(0, 10)),
        contact: String(raw.mobile1 ?? ""),
        email: String(raw.email ?? ""),
        description,
        priority,
        passenger: {
          firstName: String(raw.passengerName ?? "").trim().split(/\s+/)[0] ?? "",
          lastName: String(raw.passengerName ?? "").trim().split(/\s+/).slice(1).join(" "),
          mobile2: raw.mobile2 ? String(raw.mobile2) : undefined,
          pnr: raw.pnr ? String(raw.pnr) : undefined,
        },
        flight: {
          airline: raw.airline ? String(raw.airline) : undefined,
          originAirport: raw.origin ? String(raw.origin) : undefined,
          destinationAirport: raw.destination ? String(raw.destination) : undefined,
        },
        baggage: {
          numberOfBags: numBags,
          weightKg: raw.weightKg ? Number(raw.weightKg) : undefined,
          color: raw.bagColor ? String(raw.bagColor) : undefined,
          type: raw.bagType ? String(raw.bagType) : undefined,
          vipPassenger: priority === "VIP",
          bagTags: [bagTag],
        },
        delivery: {
          method,
          fullAddress: raw.deliveryAddress ? String(raw.deliveryAddress) : undefined,
        },
        internal: {
          createdBy: ctx.actor,
          casePriority: priority,
          internalNotes: raw.notes ? String(raw.notes) : undefined,
        },
        incomplete: incomplete || undefined,
        missingFields: incomplete ? missingFields : undefined,
        });
      } catch {
        // Rejected by the Workflow Engine (duplicate PIR / bag tag). No case
        // number is consumed, so numbering stays gapless.
        rejected++;
        continue;
      }
      if (!c) {
        rejected++;
        continue;
      }
      ids.push(c.bagId);
      created++;
    }
    return { created, updated: 0, skipped: 0, warnings, rejected, ids };
  },
};

// ---------------- Read-only / export-first datasets ----------------
// Import for these will be wired in later phases via `apply`.
function readOnly(
  id: string,
  label: string,
  description: string,
  fields: FieldDef[],
  read: () => Record<string, unknown>[],
): DatasetSchema {
  return {
    id,
    label,
    description,
    templateVersion: "1.0",
    fields,
    read,
    apply: () => ({ created: 0, updated: 0, skipped: 0, ids: [] }),
  };
}

export const deliverySchema = readOnly(
  "delivery",
  "Delivery Management",
  "Home delivery orders — passenger, driver, ETA, OTP.",
  [
    { key: "deliveryId", label: "Delivery ID", type: "string", required: true, unique: true, example: "DEL-50012" },
    { key: "bagId", label: "Bag ID", type: "string", required: true, example: "BAG-100234" },
    { key: "passengerName", label: "Passenger Name", type: "string", required: true },
    { key: "pirNumber", label: "PIR Number", type: "string", required: true },
    { key: "mobile", label: "Mobile", type: "phone", required: true },
    { key: "address", label: "Address", type: "string", required: true },
    { key: "priority", label: "Priority", type: "enum", enumValues: PRIORITY_VALUES },
    { key: "driver", label: "Delivery Agent", type: "string" },
    { key: "eta", label: "ETA", type: "datetime" },
    { key: "status", label: "Status", type: "string" },
    { key: "otpStatus", label: "OTP Status", type: "string" },
  ],
  () => getState().deliveries as unknown[] as Record<string, unknown>[],
);

export const feedbackSchema = readOnly(
  "feedback",
  "Feedback",
  "Passenger feedback with ratings and comments.",
  [
    { key: "id", label: "Feedback ID", type: "string", required: true, unique: true },
    { key: "bagId", label: "Bag ID", type: "string", required: true },
    { key: "passengerName", label: "Passenger", type: "string", required: true },
    { key: "rating", label: "Rating", type: "integer", required: true },
    { key: "resolved", label: "Resolved", type: "boolean" },
    { key: "comments", label: "Comments", type: "string" },
    { key: "at", label: "Submitted At", type: "datetime" },
  ],
  () => getState().feedback as unknown[] as Record<string, unknown>[],
);

export const qualitySchema = readOnly(
  "quality",
  "Quality Incidents",
  "Operational quality incidents raised across the workflow.",
  [
    { key: "id", label: "Incident ID", type: "string", required: true, unique: true },
    { key: "bagId", label: "Bag ID", type: "string" },
    { key: "deliveryId", label: "Delivery ID", type: "string" },
    { key: "passengerName", label: "Passenger", type: "string" },
    { key: "driver", label: "Delivery Agent", type: "string" },
    { key: "category", label: "Category", type: "string", required: true },
    { key: "severity", label: "Severity", type: "string" },
    { key: "status", label: "Status", type: "string" },
    { key: "description", label: "Description", type: "string" },
    { key: "at", label: "Reported At", type: "datetime" },
  ],
  () => getState().qualityIncidents as unknown[] as Record<string, unknown>[],
);

export const storageSchema = readOnly(
  "storage",
  "Storage Control",
  "Bags currently stored across zones/shelves.",
  [
    { key: "bagId", label: "Bag ID", type: "string", required: true, unique: true },
    { key: "passengerName", label: "Passenger", type: "string" },
    { key: "pirNumber", label: "PIR Number", type: "string" },
    { key: "zone", label: "Zone", type: "string" },
    { key: "shelf", label: "Shelf", type: "string" },
    { key: "position", label: "Position", type: "string" },
    { key: "status", label: "Status", type: "string" },
  ],
  () =>
    getState()
      .cases.filter((c) => c.storage)
      .map((c) => ({
        bagId: c.bagId,
        passengerName: c.passengerName,
        pirNumber: c.pirNumber,
        zone: c.storage?.zone ?? "",
        shelf: c.storage?.shelf ?? "",
        position: c.storage?.position ?? "",
        status: c.status,
      })),
);

export const contactSchema = readOnly(
  "contact-center",
  "Contact Center",
  "Call log history across passenger touchpoints.",
  [
    { key: "id", label: "Call ID", type: "string", required: true, unique: true },
    { key: "passengerName", label: "Passenger", type: "string", required: true },
    { key: "phone", label: "Phone", type: "phone" },
    { key: "pirNumber", label: "PIR Number", type: "string" },
    { key: "agent", label: "Agent", type: "string" },
    { key: "direction", label: "Direction", type: "string" },
    { key: "durationSec", label: "Duration (sec)", type: "integer" },
    { key: "notes", label: "Notes", type: "string" },
    { key: "at", label: "Timestamp", type: "datetime" },
  ],
  () => getState().callLogs as unknown[] as Record<string, unknown>[],
);

export const driverSchema = readOnly(
  "driver-portal",
  "Delivery Agent Portal",
  "Deliveries currently assigned to drivers.",
  deliverySchema.fields,
  () =>
    (getState().deliveries as unknown[] as Record<string, unknown>[]).filter(
      (d) => d.driver && d.driver !== "—",
    ),
);

export const passengerTrackingSchema = readOnly(
  "passenger-tracking",
  "Passenger Tracking",
  "Live tracked deliveries with tokenised passenger portal.",
  [
    { key: "deliveryId", label: "Delivery ID", type: "string", required: true, unique: true },
    { key: "status", label: "Workflow Status", type: "string", required: true },
    { key: "bagId", label: "Bag ID", type: "string" },
    { key: "token", label: "Tracking Token", type: "string" },
  ],
  () => getState().workflow as unknown[] as Record<string, unknown>[],
);

import { getAdminState } from "@/lib/admin/data";
function adminSnapshot() { return getAdminState(); }

export const usersSchema = readOnly(
  "users",
  "Users",
  "Enterprise directory of ground-handling personnel.",
  [
    { key: "id", label: "Employee ID", type: "string", required: true, unique: true },
    { key: "fullName", label: "Full Name", type: "string", required: true },
    { key: "email", label: "Email", type: "email", required: true, unique: true },
    { key: "mobile", label: "Mobile", type: "phone" },
    { key: "department", label: "Department", type: "string", required: true },
    { key: "position", label: "Position", type: "string" },
    { key: "station", label: "Station", type: "string", required: true },
    { key: "role", label: "Role", type: "string", required: true },
    { key: "status", label: "Status", type: "string" },
  ],
  () => adminSnapshot().users as unknown[] as Record<string, unknown>[],
);

export const departmentsSchema = readOnly(
  "departments",
  "Departments",
  "Ground handling departments.",
  [
    { key: "id", label: "Department ID", type: "string", required: true, unique: true },
    { key: "name", label: "Name", type: "string", required: true },
    { key: "head", label: "Head", type: "string" },
    { key: "description", label: "Description", type: "string" },
  ],
  () => adminSnapshot().departments as unknown[] as Record<string, unknown>[],
);

export const stationsSchema = readOnly(
  "stations",
  "Stations",
  "Airport stations covered by the ecosystem.",
  [
    { key: "id", label: "Station ID", type: "string", required: true, unique: true },
    { key: "code", label: "IATA Code", type: "airportCode", required: true },
    { key: "name", label: "Name", type: "string", required: true },
    { key: "city", label: "City", type: "string" },
    { key: "country", label: "Country", type: "string" },
    { key: "active", label: "Active", type: "boolean" },
  ],
  () => adminSnapshot().stations as unknown[] as Record<string, unknown>[],
);

export const teamsSchema = readOnly(
  "teams",
  "Teams",
  "Operational teams grouped by department and station.",
  [
    { key: "id", label: "Team ID", type: "string", required: true, unique: true },
    { key: "name", label: "Name", type: "string", required: true },
    { key: "department", label: "Department", type: "string" },
    { key: "station", label: "Station", type: "string" },
    { key: "lead", label: "Lead", type: "string" },
    { key: "memberCount", label: "Members", type: "integer" },
  ],
  () => adminSnapshot().teams as unknown[] as Record<string, unknown>[],
);

export const reportsSchema = readOnly(
  "reports",
  "Reports",
  "Consolidated reporting snapshot across the ecosystem.",
  lostFoundFields.slice(0, 10),
  () => getState().cases as unknown[] as Record<string, unknown>[],
);

export const IO_REGISTRY: DatasetSchema[] = [
  lostFoundSchema,
  storageSchema,
  deliverySchema,
  driverSchema,
  passengerTrackingSchema,
  contactSchema,
  feedbackSchema,
  qualitySchema,
  reportsSchema,
  usersSchema,
  departmentsSchema,
  stationsSchema,
  teamsSchema,
];

export function getSchema(id: string) {
  return IO_REGISTRY.find((s) => s.id === id);
}