/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowMonitorRouteImport } from './routes/workflow-monitor'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RouteTrackingRouteImport } from './routes/route-tracking'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QrScanRouteImport } from './routes/qr-scan'
import { Route as PassengerRouteImport } from './routes/passenger'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LostFoundRouteImport } from './routes/lost-found'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as ExportCenterRouteImport } from './routes/export-center'
import { Route as DriverPortalRouteImport } from './routes/driver-portal'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as DataIoRouteImport } from './routes/data-io'
import { Route as ContactCenterRouteImport } from './routes/contact-center'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiStatusRouteImport } from './routes/api-status'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PassengerIndexRouteImport } from './routes/passenger.index'
import { Route as LostFoundIndexRouteImport } from './routes/lost-found.index'
import { Route as DeliveryIndexRouteImport } from './routes/delivery.index'
import { Route as PassengerTokenRouteImport } from './routes/passenger.$token'
import { Route as LostFoundBagIdRouteImport } from './routes/lost-found.$bagId'
import { Route as DeliveryDeliveryIdRouteImport } from './routes/delivery.$deliveryId'

const WorkflowMonitorRoute = WorkflowMonitorRouteImport.update({
  id: '/workflow-monitor',
  path: '/workflow-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteTrackingRoute = RouteTrackingRouteImport.update({
  id: '/route-tracking',
  path: '/route-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QrScanRoute = QrScanRouteImport.update({
  id: '/qr-scan',
  path: '/qr-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerRoute = PassengerRouteImport.update({
  id: '/passenger',
  path: '/passenger',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LostFoundRoute = LostFoundRouteImport.update({
  id: '/lost-found',
  path: '/lost-found',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportCenterRoute = ExportCenterRouteImport.update({
  id: '/export-center',
  path: '/export-center',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverPortalRoute = DriverPortalRouteImport.update({
  id: '/driver-portal',
  path: '/driver-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIoRoute = DataIoRouteImport.update({
  id: '/data-io',
  path: '/data-io',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactCenterRoute = ContactCenterRouteImport.update({
  id: '/contact-center',
  path: '/contact-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api-status',
  path: '/api-status',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerIndexRoute = PassengerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PassengerRoute,
} as any)
const LostFoundIndexRoute = LostFoundIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LostFoundRoute,
} as any)
const DeliveryIndexRoute = DeliveryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeliveryRoute,
} as any)
const PassengerTokenRoute = PassengerTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => PassengerRoute,
} as any)
const LostFoundBagIdRoute = LostFoundBagIdRouteImport.update({
  id: '/$bagId',
  path: '/$bagId',
  getParentRoute: () => LostFoundRoute,
} as any)
const DeliveryDeliveryIdRoute = DeliveryDeliveryIdRouteImport.update({
  id: '/$deliveryId',
  path: '/$deliveryId',
  getParentRoute: () => DeliveryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-status': typeof ApiStatusRoute
  '/auth': typeof AuthRoute
  '/contact-center': typeof ContactCenterRoute
  '/data-io': typeof DataIoRoute
  '/delivery': typeof DeliveryRouteWithChildren
  '/driver-portal': typeof DriverPortalRoute
  '/export-center': typeof ExportCenterRoute
  '/feedback': typeof FeedbackRoute
  '/integrations': typeof IntegrationsRoute
  '/lost-found': typeof LostFoundRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/passenger': typeof PassengerRouteWithChildren
  '/qr-scan': typeof QrScanRoute
  '/reports': typeof ReportsRoute
  '/route-tracking': typeof RouteTrackingRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/timeline': typeof TimelineRoute
  '/tracking': typeof TrackingRoute
  '/workflow-monitor': typeof WorkflowMonitorRoute
  '/delivery/$deliveryId': typeof DeliveryDeliveryIdRoute
  '/lost-found/$bagId': typeof LostFoundBagIdRoute
  '/passenger/$token': typeof PassengerTokenRoute
  '/delivery/': typeof DeliveryIndexRoute
  '/lost-found/': typeof LostFoundIndexRoute
  '/passenger/': typeof PassengerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-status': typeof ApiStatusRoute
  '/auth': typeof AuthRoute
  '/contact-center': typeof ContactCenterRoute
  '/data-io': typeof DataIoRoute
  '/driver-portal': typeof DriverPortalRoute
  '/export-center': typeof ExportCenterRoute
  '/feedback': typeof FeedbackRoute
  '/integrations': typeof IntegrationsRoute
  '/notifications': typeof NotificationsRoute
  '/qr-scan': typeof QrScanRoute
  '/reports': typeof ReportsRoute
  '/route-tracking': typeof RouteTrackingRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/timeline': typeof TimelineRoute
  '/tracking': typeof TrackingRoute
  '/workflow-monitor': typeof WorkflowMonitorRoute
  '/delivery/$deliveryId': typeof DeliveryDeliveryIdRoute
  '/lost-found/$bagId': typeof LostFoundBagIdRoute
  '/passenger/$token': typeof PassengerTokenRoute
  '/delivery': typeof DeliveryIndexRoute
  '/lost-found': typeof LostFoundIndexRoute
  '/passenger': typeof PassengerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-status': typeof ApiStatusRoute
  '/auth': typeof AuthRoute
  '/contact-center': typeof ContactCenterRoute
  '/data-io': typeof DataIoRoute
  '/delivery': typeof DeliveryRouteWithChildren
  '/driver-portal': typeof DriverPortalRoute
  '/export-center': typeof ExportCenterRoute
  '/feedback': typeof FeedbackRoute
  '/integrations': typeof IntegrationsRoute
  '/lost-found': typeof LostFoundRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/passenger': typeof PassengerRouteWithChildren
  '/qr-scan': typeof QrScanRoute
  '/reports': typeof ReportsRoute
  '/route-tracking': typeof RouteTrackingRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/timeline': typeof TimelineRoute
  '/tracking': typeof TrackingRoute
  '/workflow-monitor': typeof WorkflowMonitorRoute
  '/delivery/$deliveryId': typeof DeliveryDeliveryIdRoute
  '/lost-found/$bagId': typeof LostFoundBagIdRoute
  '/passenger/$token': typeof PassengerTokenRoute
  '/delivery/': typeof DeliveryIndexRoute
  '/lost-found/': typeof LostFoundIndexRoute
  '/passenger/': typeof PassengerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-status'
    | '/auth'
    | '/contact-center'
    | '/data-io'
    | '/delivery'
    | '/driver-portal'
    | '/export-center'
    | '/feedback'
    | '/integrations'
    | '/lost-found'
    | '/notifications'
    | '/passenger'
    | '/qr-scan'
    | '/reports'
    | '/route-tracking'
    | '/settings'
    | '/storage'
    | '/timeline'
    | '/tracking'
    | '/workflow-monitor'
    | '/delivery/$deliveryId'
    | '/lost-found/$bagId'
    | '/passenger/$token'
    | '/delivery/'
    | '/lost-found/'
    | '/passenger/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-status'
    | '/auth'
    | '/contact-center'
    | '/data-io'
    | '/driver-portal'
    | '/export-center'
    | '/feedback'
    | '/integrations'
    | '/notifications'
    | '/qr-scan'
    | '/reports'
    | '/route-tracking'
    | '/settings'
    | '/storage'
    | '/timeline'
    | '/tracking'
    | '/workflow-monitor'
    | '/delivery/$deliveryId'
    | '/lost-found/$bagId'
    | '/passenger/$token'
    | '/delivery'
    | '/lost-found'
    | '/passenger'
  id:
    | '__root__'
    | '/'
    | '/api-status'
    | '/auth'
    | '/contact-center'
    | '/data-io'
    | '/delivery'
    | '/driver-portal'
    | '/export-center'
    | '/feedback'
    | '/integrations'
    | '/lost-found'
    | '/notifications'
    | '/passenger'
    | '/qr-scan'
    | '/reports'
    | '/route-tracking'
    | '/settings'
    | '/storage'
    | '/timeline'
    | '/tracking'
    | '/workflow-monitor'
    | '/delivery/$deliveryId'
    | '/lost-found/$bagId'
    | '/passenger/$token'
    | '/delivery/'
    | '/lost-found/'
    | '/passenger/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiStatusRoute: typeof ApiStatusRoute
  AuthRoute: typeof AuthRoute
  ContactCenterRoute: typeof ContactCenterRoute
  DataIoRoute: typeof DataIoRoute
  DeliveryRoute: typeof DeliveryRouteWithChildren
  DriverPortalRoute: typeof DriverPortalRoute
  ExportCenterRoute: typeof ExportCenterRoute
  FeedbackRoute: typeof FeedbackRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LostFoundRoute: typeof LostFoundRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  PassengerRoute: typeof PassengerRouteWithChildren
  QrScanRoute: typeof QrScanRoute
  ReportsRoute: typeof ReportsRoute
  RouteTrackingRoute: typeof RouteTrackingRoute
  SettingsRoute: typeof SettingsRoute
  StorageRoute: typeof StorageRoute
  TimelineRoute: typeof TimelineRoute
  TrackingRoute: typeof TrackingRoute
  WorkflowMonitorRoute: typeof WorkflowMonitorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow-monitor': {
      id: '/workflow-monitor'
      path: '/workflow-monitor'
      fullPath: '/workflow-monitor'
      preLoaderRoute: typeof WorkflowMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-tracking': {
      id: '/route-tracking'
      path: '/route-tracking'
      fullPath: '/route-tracking'
      preLoaderRoute: typeof RouteTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-scan': {
      id: '/qr-scan'
      path: '/qr-scan'
      fullPath: '/qr-scan'
      preLoaderRoute: typeof QrScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger': {
      id: '/passenger'
      path: '/passenger'
      fullPath: '/passenger'
      preLoaderRoute: typeof PassengerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lost-found': {
      id: '/lost-found'
      path: '/lost-found'
      fullPath: '/lost-found'
      preLoaderRoute: typeof LostFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-center': {
      id: '/export-center'
      path: '/export-center'
      fullPath: '/export-center'
      preLoaderRoute: typeof ExportCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-portal': {
      id: '/driver-portal'
      path: '/driver-portal'
      fullPath: '/driver-portal'
      preLoaderRoute: typeof DriverPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-io': {
      id: '/data-io'
      path: '/data-io'
      fullPath: '/data-io'
      preLoaderRoute: typeof DataIoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-center': {
      id: '/contact-center'
      path: '/contact-center'
      fullPath: '/contact-center'
      preLoaderRoute: typeof ContactCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-status': {
      id: '/api-status'
      path: '/api-status'
      fullPath: '/api-status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/': {
      id: '/passenger/'
      path: '/'
      fullPath: '/passenger/'
      preLoaderRoute: typeof PassengerIndexRouteImport
      parentRoute: typeof PassengerRoute
    }
    '/lost-found/': {
      id: '/lost-found/'
      path: '/'
      fullPath: '/lost-found/'
      preLoaderRoute: typeof LostFoundIndexRouteImport
      parentRoute: typeof LostFoundRoute
    }
    '/delivery/': {
      id: '/delivery/'
      path: '/'
      fullPath: '/delivery/'
      preLoaderRoute: typeof DeliveryIndexRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/passenger/$token': {
      id: '/passenger/$token'
      path: '/$token'
      fullPath: '/passenger/$token'
      preLoaderRoute: typeof PassengerTokenRouteImport
      parentRoute: typeof PassengerRoute
    }
    '/lost-found/$bagId': {
      id: '/lost-found/$bagId'
      path: '/$bagId'
      fullPath: '/lost-found/$bagId'
      preLoaderRoute: typeof LostFoundBagIdRouteImport
      parentRoute: typeof LostFoundRoute
    }
    '/delivery/$deliveryId': {
      id: '/delivery/$deliveryId'
      path: '/$deliveryId'
      fullPath: '/delivery/$deliveryId'
      preLoaderRoute: typeof DeliveryDeliveryIdRouteImport
      parentRoute: typeof DeliveryRoute
    }
  }
}

interface DeliveryRouteChildren {
  DeliveryDeliveryIdRoute: typeof DeliveryDeliveryIdRoute
  DeliveryIndexRoute: typeof DeliveryIndexRoute
}

const DeliveryRouteChildren: DeliveryRouteChildren = {
  DeliveryDeliveryIdRoute: DeliveryDeliveryIdRoute,
  DeliveryIndexRoute: DeliveryIndexRoute,
}

const DeliveryRouteWithChildren = DeliveryRoute._addFileChildren(
  DeliveryRouteChildren,
)

interface LostFoundRouteChildren {
  LostFoundBagIdRoute: typeof LostFoundBagIdRoute
  LostFoundIndexRoute: typeof LostFoundIndexRoute
}

const LostFoundRouteChildren: LostFoundRouteChildren = {
  LostFoundBagIdRoute: LostFoundBagIdRoute,
  LostFoundIndexRoute: LostFoundIndexRoute,
}

const LostFoundRouteWithChildren = LostFoundRoute._addFileChildren(
  LostFoundRouteChildren,
)

interface PassengerRouteChildren {
  PassengerTokenRoute: typeof PassengerTokenRoute
  PassengerIndexRoute: typeof PassengerIndexRoute
}

const PassengerRouteChildren: PassengerRouteChildren = {
  PassengerTokenRoute: PassengerTokenRoute,
  PassengerIndexRoute: PassengerIndexRoute,
}

const PassengerRouteWithChildren = PassengerRoute._addFileChildren(
  PassengerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiStatusRoute: ApiStatusRoute,
  AuthRoute: AuthRoute,
  ContactCenterRoute: ContactCenterRoute,
  DataIoRoute: DataIoRoute,
  DeliveryRoute: DeliveryRouteWithChildren,
  DriverPortalRoute: DriverPortalRoute,
  ExportCenterRoute: ExportCenterRoute,
  FeedbackRoute: FeedbackRoute,
  IntegrationsRoute: IntegrationsRoute,
  LostFoundRoute: LostFoundRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  PassengerRoute: PassengerRouteWithChildren,
  QrScanRoute: QrScanRoute,
  ReportsRoute: ReportsRoute,
  RouteTrackingRoute: RouteTrackingRoute,
  SettingsRoute: SettingsRoute,
  StorageRoute: StorageRoute,
  TimelineRoute: TimelineRoute,
  TrackingRoute: TrackingRoute,
  WorkflowMonitorRoute: WorkflowMonitorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
