/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LostFoundRouteImport } from './routes/lost-found'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as IndexRouteImport } from './routes/index'

const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LostFoundRoute = LostFoundRouteImport.update({
  id: '/lost-found',
  path: '/lost-found',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/delivery': typeof DeliveryRoute
  '/lost-found': typeof LostFoundRoute
  '/reports': typeof ReportsRoute
  '/storage': typeof StorageRoute
  '/tracking': typeof TrackingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/delivery': typeof DeliveryRoute
  '/lost-found': typeof LostFoundRoute
  '/reports': typeof ReportsRoute
  '/storage': typeof StorageRoute
  '/tracking': typeof TrackingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/delivery': typeof DeliveryRoute
  '/lost-found': typeof LostFoundRoute
  '/reports': typeof ReportsRoute
  '/storage': typeof StorageRoute
  '/tracking': typeof TrackingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/delivery'
    | '/lost-found'
    | '/reports'
    | '/storage'
    | '/tracking'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/delivery' | '/lost-found' | '/reports' | '/storage' | '/tracking'
  id:
    | '__root__'
    | '/'
    | '/delivery'
    | '/lost-found'
    | '/reports'
    | '/storage'
    | '/tracking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeliveryRoute: typeof DeliveryRoute
  LostFoundRoute: typeof LostFoundRoute
  ReportsRoute: typeof ReportsRoute
  StorageRoute: typeof StorageRoute
  TrackingRoute: typeof TrackingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lost-found': {
      id: '/lost-found'
      path: '/lost-found'
      fullPath: '/lost-found'
      preLoaderRoute: typeof LostFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeliveryRoute: DeliveryRoute,
  LostFoundRoute: LostFoundRoute,
  ReportsRoute: ReportsRoute,
  StorageRoute: StorageRoute,
  TrackingRoute: TrackingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
