// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxjuhoghypsbuqquhxib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4anVob2doeXBzYnVxcXVoeGliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQxMTM1NTQsImV4cCI6MjA5OTY4OTU1NH0.s3an6t0YOBzU0-tvkmDIwyNzNxqpXDwN4kZTwObbxyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});